/* VectorEnginePlugin: Cuis's vector graphics rasterizer, hand-translated to JS.
 *
 * Source of truth: utils/VectorEnginePlugin.ref/VectorEnginePlugin.c — the exact
 * file the native VMs compile, generated upstream from VectorEnginePlugin-jmv.26
 * (uuid 4a7f4646-3609-4ce7-8e92-81a5f13c8ce5). This file follows that C function
 * by function so the two stay diffable; it is written by hand, not generated
 * (there is no "generated by" header on purpose — see CLAUDE.md on plugins/).
 *
 * The image (VectorEngineWithPlugin class>>isPluginAvailable) switches its whole
 * rendering engine on ONE question: does the named primitive 'pluginApiVersion'
 * of this module answer exactly 7. There is no per-primitive fallback: if we
 * answer 7 and a primitive is missing or wrong, rendering breaks instead of
 * degrading. Hence the guard below: pluginApiVersion only answers 7 once every
 * primitive of the API is implemented (or, while developing, when
 * Squeak.enableVectorEnginePlugin is set to true by a test harness); otherwise
 * it fails and the image keeps its pure-Smalltalk engine, same as today.
 *
 * Numeric policy (measured against the in-image Smalltalk engine as oracle):
 * C float state is kept as JS doubles — the Smalltalk engine computes in 64-bit
 * floats too, so doubles keep us inside the difference band Cuis already accepts
 * between native plugin and Smalltalk engine. Integer pixel work (edgeCounts /
 * alphaMask packing, blending) is translated bit-exactly with >>>, & and |0.
 */

(function VectorEnginePlugin() {
"use strict";

var interpreterProxy = null;
var moduleName = "VectorEnginePlugin VectorEnginePlugin-jmv.26 (j)";

// Set to true (Squeak.enableVectorEnginePlugin) to let the image use the plugin
// before ALL primitives are done. Never ship a default of true while any
// primitive below still fails: see the header.
var COMPLETE = false;   // flip when the whole API is implemented and validated

/*** state (the C file's static variables, same names) ***/

var affectedBits = null;        // uint8_t*
var alphaMask = null;           // uint32_t*
var alphaMaskWP = null;         // uint8_t*
var clippingSpec = null;        // int*
var clipLeft = 0, clipTop = 0, clipRight = 0, clipBottom = 0;
var contour = null;             // float*
var currentMorphId = 0;
var dashBitCount = 0, dashBitOffset = 0, dashedStrokeBits = 0;
var dashBitLength = 0.0;
var edgeCounts = null;          // uint32_t*
var edgeCountsWP = null;        // uint8_t*
var morphIds = null;            // uint32_t*
var needsFullAlphaCircle = 0;
var prevYRounded = 0, prevYTruncated = 0;
var targetAssumedOpaque = 0;
var targetBits = null;          // uint32_t*
var targetWidth = 0, targetHeight = 0;
var antiAliasingWidth = 0.0, subPixelDelta = 0.0;
var auxAntiAliasingWidthScaledInverse = 0.0;
var auxStrokeWidthDilatedHalf = 0.0;
var auxStrokeWidthDilatedHalfSquared = 0.0;
var auxStrokeWidthErodedHalfSquared = 0.0;
var fillR = 0.0, fillG = 0.0, fillB = 0.0, fillA = 0.0;
var strokeR = 0.0, strokeG = 0.0, strokeB = 0.0, strokeA = 0.0;
var strokeWidth = 0.0, hop = 0.0;
var leftAtThisY = 0.0, rightAtThisY = 0.0;
var spanLeft = 0.0, spanTop = 0.0, spanRight = 0.0, spanBottom = 0.0;
var trajectoryLength = 0.0;
var txA11 = 0.0, txA12 = 0.0, txA13 = 0.0, txA21 = 0.0, txA22 = 0.0, txA23 = 0.0;

/*** the C plugin ABI over the SqueakJS interpreterProxy ***/

var PrimErrBadArgument = 3;

function stackValue(n) { return interpreterProxy.stackValue(n); }
function failed() { return interpreterProxy.failed(); }
function pop(n) { interpreterProxy.pop(n); }
function primitiveFailFor(code) { interpreterProxy.primitiveFailFor(code); }
function isWords(oop) { return interpreterProxy.isWords(oop); }
function isBytes(oop) { return interpreterProxy.isBytes(oop); }
function isWordsOrBytes(oop) { return interpreterProxy.isWordsOrBytes(oop); }
function isIntegerObject(oop) { return typeof oop === "number"; }
function integerValueOf(oop) { return oop; }
function integerObjectOf(value) { return value; }
function isFloatObject(oop) {
    // the C's stackFloatValue only takes real Floats; the image sends Floats here
    return typeof oop === "object" && !!oop.isFloat;
}
function stackFloatValue(n) { return stackValue(n).float; }   // only called after isFloatObject
function isBooleanObject(oop) {
    return oop === interpreterProxy.trueObject() || oop === interpreterProxy.falseObject();
}
function booleanValueOf(oop) { return oop === interpreterProxy.trueObject() ? 1 : 0; }
function methodReturnValue(oop) {
    interpreterProxy.popthenPush(interpreterProxy.methodArgumentCount() + 1, oop);
}

// the C casts firstIndexableField to a typed pointer; here each use site picks
// the typed view it needs. Float32Array data lives in .words in SqueakJS, so the
// float view shares the same buffer (writes through either are seen by both).
function wordsOf(oop) { return oop.words; }                       // uint32_t*
function bytesOf(oop) { return oop.bytes; }                       // uint8_t*
function int32Of(oop) { return oop.wordsAsInt32Array(); }         // int*
function float32Of(oop) { return oop.wordsAsFloat32Array(); }     // float*

/*** primitives, in the C file's order where possible ***/

function dashedStrokeBitsSet(argCount) {
    var onOffBitSequence, numberOfBitsInSequence, offset;
    if (!(isIntegerObject((onOffBitSequence = stackValue(3)))
        && isIntegerObject((numberOfBitsInSequence = stackValue(2)))
        && isFloatObject(stackValue(1))
        && isIntegerObject((offset = stackValue(0))))) {
        primitiveFailFor(PrimErrBadArgument); return false;
    }
    dashedStrokeBits = onOffBitSequence;
    dashBitCount = numberOfBitsInSequence;
    dashBitLength = stackFloatValue(1);
    dashBitOffset = offset;
    if (!failed()) pop(4);
    return !failed();
}

function pluginApiVersion(argCount) {
    // THE gate: answering 7 switches the image's whole rendering engine over to
    // this module, with no per-primitive fallback. See the header.
    if (!COMPLETE && !(typeof Squeak === "object" && Squeak.enableVectorEnginePlugin))
        return false;
    methodReturnValue(integerObjectOf(7));
    return true;
}

function primAntiAliasingWidthsubPixelDelta(argCount) {
    if (!(isFloatObject(stackValue(1)) && isFloatObject(stackValue(0)))) {
        primitiveFailFor(PrimErrBadArgument); return false;
    }
    antiAliasingWidth = stackFloatValue(1);
    subPixelDelta = stackFloatValue(0);
    auxAntiAliasingWidthScaledInverse = 127.0 / antiAliasingWidth;
    if (!failed()) pop(2);
    return !failed();
}

function primClearClippingSpec(argCount) {
    clippingSpec = null;
    return true;
}

function primClipLeftclipTopclipRightclipBottom(argCount) {
    var l, t, r, b;
    if (!(isIntegerObject((l = stackValue(3)))
        && isIntegerObject((t = stackValue(2)))
        && isIntegerObject((r = stackValue(1)))
        && isIntegerObject((b = stackValue(0))))) {
        primitiveFailFor(PrimErrBadArgument); return false;
    }
    clipLeft = l; clipTop = t; clipRight = r; clipBottom = b;
    if (!failed()) pop(4);
    return !failed();
}

function primCurrentMorphId(argCount) {
    var aNumber;
    if (!isIntegerObject((aNumber = stackValue(0)))) {
        primitiveFailFor(PrimErrBadArgument); return false;
    }
    currentMorphId = aNumber >>> 0;
    if (!failed()) pop(1);
    return !failed();
}

function primFillRGBA(argCount) {
    if (!(isFloatObject(stackValue(3)) && isFloatObject(stackValue(2))
        && isFloatObject(stackValue(1)) && isFloatObject(stackValue(0)))) {
        primitiveFailFor(PrimErrBadArgument); return false;
    }
    fillR = stackFloatValue(3) * 255.0;
    fillG = stackFloatValue(2) * 255.0;
    fillB = stackFloatValue(1) * 255.0;
    fillA = stackFloatValue(0);
    if (!failed()) pop(4);
    return !failed();
}

function primGeometryTxSet(argCount) {
    if (!(isFloatObject(stackValue(5)) && isFloatObject(stackValue(4))
        && isFloatObject(stackValue(3)) && isFloatObject(stackValue(2))
        && isFloatObject(stackValue(1)) && isFloatObject(stackValue(0)))) {
        primitiveFailFor(PrimErrBadArgument); return false;
    }
    txA11 = stackFloatValue(5); txA12 = stackFloatValue(4); txA13 = stackFloatValue(3);
    txA21 = stackFloatValue(2); txA22 = stackFloatValue(1); txA23 = stackFloatValue(0);
    if (!failed()) pop(6);
    return !failed();
}

function primInitializePath(argCount) {
    spanLeft = targetWidth;      // drawable right. Will later be refined.
    spanTop = targetHeight;      // drawable bottom. Will later be refined.
    spanRight = 0;               // drawable left. Will later be refined.
    spanBottom = 0;              // drawable top. Will later be refined.
    prevYRounded = 0x7FFFFFFF;
    return true;
}

function primLine(argCount) {
    if (!(isFloatObject(stackValue(3)) && isFloatObject(stackValue(2))
        && isFloatObject(stackValue(1)) && isFloatObject(stackValue(0)))) {
        primitiveFailFor(PrimErrBadArgument); return false;
    }
    pvt_lineFromXytoXy(stackFloatValue(3), stackFloatValue(2),
                       stackFloatValue(1), stackFloatValue(0));
    if (!failed()) pop(4);
    return !failed();
}

function primLineWP(argCount) {
    if (!(isFloatObject(stackValue(3)) && isFloatObject(stackValue(2))
        && isFloatObject(stackValue(1)) && isFloatObject(stackValue(0)))) {
        primitiveFailFor(PrimErrBadArgument); return false;
    }
    pvt_lineWPFromXytoXy(stackFloatValue(3), stackFloatValue(2),
                         stackFloatValue(1), stackFloatValue(0));
    if (!failed()) pop(4);
    return !failed();
}

function primQuadraticBezier(argCount) {
    if (!(isFloatObject(stackValue(5)) && isFloatObject(stackValue(4))
        && isFloatObject(stackValue(3)) && isFloatObject(stackValue(2))
        && isFloatObject(stackValue(1)) && isFloatObject(stackValue(0)))) {
        primitiveFailFor(PrimErrBadArgument); return false;
    }
    pvt_quadraticBezierFromXytoXycontrolXy(
        stackFloatValue(5), stackFloatValue(4), stackFloatValue(3),
        stackFloatValue(2), stackFloatValue(1), stackFloatValue(0));
    if (!failed()) pop(6);
    return !failed();
}

function primQuadraticBezierWP(argCount) {
    if (!(isFloatObject(stackValue(5)) && isFloatObject(stackValue(4))
        && isFloatObject(stackValue(3)) && isFloatObject(stackValue(2))
        && isFloatObject(stackValue(1)) && isFloatObject(stackValue(0)))) {
        primitiveFailFor(PrimErrBadArgument); return false;
    }
    pvt_quadraticBezierWPFromXytoXycontrolXy(
        stackFloatValue(5), stackFloatValue(4), stackFloatValue(3),
        stackFloatValue(2), stackFloatValue(1), stackFloatValue(0));
    if (!failed()) pop(6);
    return !failed();
}

function primCubicBezier(argCount) {
    if (!(isFloatObject(stackValue(7)) && isFloatObject(stackValue(6))
        && isFloatObject(stackValue(5)) && isFloatObject(stackValue(4))
        && isFloatObject(stackValue(3)) && isFloatObject(stackValue(2))
        && isFloatObject(stackValue(1)) && isFloatObject(stackValue(0)))) {
        primitiveFailFor(PrimErrBadArgument); return false;
    }
    pvt_cubicBezierFromXytoXycontrol1Xycontrol2Xy(
        stackFloatValue(7), stackFloatValue(6), stackFloatValue(5), stackFloatValue(4),
        stackFloatValue(3), stackFloatValue(2), stackFloatValue(1), stackFloatValue(0));
    if (!failed()) pop(8);
    return !failed();
}

function primCubicBezierWP(argCount) {
    if (!(isFloatObject(stackValue(7)) && isFloatObject(stackValue(6))
        && isFloatObject(stackValue(5)) && isFloatObject(stackValue(4))
        && isFloatObject(stackValue(3)) && isFloatObject(stackValue(2))
        && isFloatObject(stackValue(1)) && isFloatObject(stackValue(0)))) {
        primitiveFailFor(PrimErrBadArgument); return false;
    }
    pvt_cubicBezierWPFromXytoXycontrol1Xycontrol2Xy(
        stackFloatValue(7), stackFloatValue(6), stackFloatValue(5), stackFloatValue(4),
        stackFloatValue(3), stackFloatValue(2), stackFloatValue(1), stackFloatValue(0));
    if (!failed()) pop(8);
    return !failed();
}

function primNewTrajectoryFragment(argCount) {
    prevYTruncated = 0x7FFFFFFF;   // initializeTrajectoryFragment
    if (!failed()) methodReturnValue(integerObjectOf(0));
    return !failed();
}

function primResetContour(argCount) {
    var t, b, y;
    if (!(isIntegerObject((t = stackValue(1)))
        && isIntegerObject((b = stackValue(0))))) {
        primitiveFailFor(PrimErrBadArgument); return false;
    }
    leftAtThisY = 1.0e6;
    rightAtThisY = 0.0;
    for (y = t; y <= b; y += 1) {
        contour[y * 2] = 1.0e6;
        contour[(y * 2) + 1] = 0.0;
    }
    if (!failed()) pop(2);
    return !failed();
}

function primSetClippingSpec(argCount) {
    if (!isWords(stackValue(0))) {
        primitiveFailFor(PrimErrBadArgument); return false;
    }
    clippingSpec = int32Of(stackValue(0));
    if (!failed()) pop(1);
    return !failed();
}

function primSetTarget(argCount) {
    var aNumber, otherNumber;
    if (!(isWords(stackValue(7)) && isWords(stackValue(6))
        && isWords(stackValue(5)) && isWords(stackValue(4))
        && isBytes(stackValue(3)) && isWordsOrBytes(stackValue(2))
        && isIntegerObject((aNumber = stackValue(1)))
        && isIntegerObject((otherNumber = stackValue(0))))) {
        primitiveFailFor(PrimErrBadArgument); return false;
    }
    targetBits = wordsOf(stackValue(7));
    morphIds = wordsOf(stackValue(6));
    edgeCounts = wordsOf(stackValue(5));
    alphaMask = wordsOf(stackValue(4));
    affectedBits = bytesOf(stackValue(3));
    contour = float32Of(stackValue(2));
    targetWidth = aNumber;
    targetHeight = otherNumber;
    clippingSpec = null;
    if (!failed()) pop(8);
    return !failed();
}

function primSetTargetWP(argCount) {
    var aNumber, otherNumber;
    if (!(isWords(stackValue(7)) && isWords(stackValue(6))
        && isBytes(stackValue(5)) && isBytes(stackValue(4))
        && isBytes(stackValue(3)) && isWordsOrBytes(stackValue(2))
        && isIntegerObject((aNumber = stackValue(1)))
        && isIntegerObject((otherNumber = stackValue(0))))) {
        primitiveFailFor(PrimErrBadArgument); return false;
    }
    targetBits = wordsOf(stackValue(7));
    morphIds = wordsOf(stackValue(6));
    edgeCountsWP = bytesOf(stackValue(5));
    alphaMaskWP = bytesOf(stackValue(4));
    affectedBits = bytesOf(stackValue(3));
    contour = float32Of(stackValue(2));
    targetWidth = aNumber;
    targetHeight = otherNumber;
    clippingSpec = null;
    if (!failed()) pop(8);
    return !failed();
}

function primSpanBottom(argCount) {
    methodReturnValue(integerObjectOf(Math.trunc(spanBottom + auxStrokeWidthDilatedHalf)));
    return true;
}

function primSpanLeft(argCount) {
    // (int(z+1)) works equally well than the more intuitive but slower (int(ceil(z))
    methodReturnValue(integerObjectOf(Math.trunc(((spanLeft - auxStrokeWidthDilatedHalf) - subPixelDelta) + 1)));
    return true;
}

function primSpanRight(argCount) {
    // Make room not just for updated mask, but also edges (hence, +1)
    methodReturnValue(integerObjectOf(Math.trunc((spanRight + auxStrokeWidthDilatedHalf) + subPixelDelta) + 1));
    return true;
}

function primSpanTop(argCount) {
    methodReturnValue(integerObjectOf(Math.trunc((spanTop - auxStrokeWidthDilatedHalf) + 1)));
    return true;
}

function primStrokeRGBA(argCount) {
    if (!(isFloatObject(stackValue(3)) && isFloatObject(stackValue(2))
        && isFloatObject(stackValue(1)) && isFloatObject(stackValue(0)))) {
        primitiveFailFor(PrimErrBadArgument); return false;
    }
    strokeR = stackFloatValue(3) * 255.0;
    strokeG = stackFloatValue(2) * 255.0;
    strokeB = stackFloatValue(1) * 255.0;
    strokeA = stackFloatValue(0);
    if (!failed()) pop(4);
    return !failed();
}

function primStrokeWidthHop(argCount) {
    var swErodedHalf;
    if (!(isFloatObject(stackValue(1)) && isFloatObject(stackValue(0)))) {
        primitiveFailFor(PrimErrBadArgument); return false;
    }
    strokeWidth = stackFloatValue(1);
    hop = stackFloatValue(0);
    auxStrokeWidthDilatedHalf = (strokeWidth + antiAliasingWidth) * 0.5;
    auxStrokeWidthDilatedHalfSquared = auxStrokeWidthDilatedHalf * auxStrokeWidthDilatedHalf;
    // swErodedHalf is the inner radious of the alphas ring.
    swErodedHalf = (((strokeWidth - antiAliasingWidth) * 0.5) - hop) - 2.0;
    auxStrokeWidthErodedHalfSquared = swErodedHalf * Math.abs(swErodedHalf);
    // Set them later with a call to dashedStrokeBits if desired.
    dashedStrokeBits = 0;
    dashBitCount = 0;
    dashBitLength = 0.0;
    dashBitOffset = 0;
    if (!failed()) pop(2);
    return !failed();
}

function primTargetAssumedOpaque(argCount) {
    if (!isBooleanObject(stackValue(0))) {
        primitiveFailFor(PrimErrBadArgument); return false;
    }
    targetAssumedOpaque = booleanValueOf(stackValue(0));
    if (!failed()) pop(1);
    return !failed();
}

function primUpdateContourLastLine(argCount) {
    updateContourLastLine();
    return !failed();
}

/*** rasterizer bodies: translated from the C file — see TRADUCCION.md ***/

function notYetTranslated() {
    // honest stub: fail the primitive so the image's engine choice (already made
    // via pluginApiVersion) is never lied to twice — this should be unreachable
    // unless the guard was forced on with the API incomplete
    interpreterProxy.primitiveFail();
    return false;
}

var pvt_lineFromXytoXy = notYetTranslated;
var pvt_lineWPFromXytoXy = notYetTranslated;
var pvt_quadraticBezierFromXytoXycontrolXy = notYetTranslated;
var pvt_quadraticBezierWPFromXytoXycontrolXy = notYetTranslated;
var pvt_cubicBezierFromXytoXycontrol1Xycontrol2Xy = notYetTranslated;
var pvt_cubicBezierWPFromXytoXycontrol1Xycontrol2Xy = notYetTranslated;
var updateContourLastLine = notYetTranslated;

var primArc = notYetTranslated;
var primArcWP = notYetTranslated;
var primBlendFillOnly = notYetTranslated;
var primBlendFillOnlyWP = notYetTranslated;
var primBlendStrokeAndFill = notYetTranslated;
var primBlendStrokeAndFillWP = notYetTranslated;
var primBlendStrokeOnly = notYetTranslated;
var primBlendStrokeOnlyWP = notYetTranslated;
var primDisplayByteString = notYetTranslated;
var primDisplayByteStringWP = notYetTranslated;
var primDisplayUtf32 = notYetTranslated;
var primDisplayUtf32WP = notYetTranslated;
var primDisplayUtf8 = notYetTranslated;
var primDisplayUtf8WP = notYetTranslated;
var primPathSequence = notYetTranslated;
var primPathSequenceWP = notYetTranslated;

/*** module plumbing ***/

function getModuleName() { return moduleName; }

function setInterpreter(anInterpreter) {
    interpreterProxy = anInterpreter;
    return interpreterProxy.majorVersion() == 1 && interpreterProxy.minorVersion() >= 11;
}

function initialiseModule() {
    // the image may unload/reload the module around snapshots: forget the target
    targetBits = morphIds = edgeCounts = edgeCountsWP = null;
    alphaMask = alphaMaskWP = affectedBits = contour = clippingSpec = null;
    return true;
}

function registerPlugin() {
    if (typeof Squeak === "object" && Squeak.registerExternalModule) {
        Squeak.registerExternalModule("VectorEnginePlugin", {
            getModuleName: getModuleName,
            setInterpreter: setInterpreter,
            initialiseModule: initialiseModule,
            pluginApiVersion: pluginApiVersion,
            dashedStrokeBitsSet: dashedStrokeBitsSet,
            primAntiAliasingWidthsubPixelDelta: primAntiAliasingWidthsubPixelDelta,
            primArc: function(argCount) { return primArc(argCount); },
            primArcWP: function(argCount) { return primArcWP(argCount); },
            primBlendFillOnly: function(argCount) { return primBlendFillOnly(argCount); },
            primBlendFillOnlyWP: function(argCount) { return primBlendFillOnlyWP(argCount); },
            primBlendStrokeAndFill: function(argCount) { return primBlendStrokeAndFill(argCount); },
            primBlendStrokeAndFillWP: function(argCount) { return primBlendStrokeAndFillWP(argCount); },
            primBlendStrokeOnly: function(argCount) { return primBlendStrokeOnly(argCount); },
            primBlendStrokeOnlyWP: function(argCount) { return primBlendStrokeOnlyWP(argCount); },
            primClearClippingSpec: primClearClippingSpec,
            primClipLeftclipTopclipRightclipBottom: primClipLeftclipTopclipRightclipBottom,
            primCubicBezier: primCubicBezier,
            primCubicBezierWP: primCubicBezierWP,
            primCurrentMorphId: primCurrentMorphId,
            primDisplayByteString: function(argCount) { return primDisplayByteString(argCount); },
            primDisplayByteStringWP: function(argCount) { return primDisplayByteStringWP(argCount); },
            primDisplayUtf32: function(argCount) { return primDisplayUtf32(argCount); },
            primDisplayUtf32WP: function(argCount) { return primDisplayUtf32WP(argCount); },
            primDisplayUtf8: function(argCount) { return primDisplayUtf8(argCount); },
            primDisplayUtf8WP: function(argCount) { return primDisplayUtf8WP(argCount); },
            primFillRGBA: primFillRGBA,
            primGeometryTxSet: primGeometryTxSet,
            primInitializePath: primInitializePath,
            primLine: primLine,
            primLineWP: primLineWP,
            primNewTrajectoryFragment: primNewTrajectoryFragment,
            primPathSequence: function(argCount) { return primPathSequence(argCount); },
            primPathSequenceWP: function(argCount) { return primPathSequenceWP(argCount); },
            primQuadraticBezier: primQuadraticBezier,
            primQuadraticBezierWP: primQuadraticBezierWP,
            primResetContour: primResetContour,
            primSetClippingSpec: primSetClippingSpec,
            primSetTarget: primSetTarget,
            primSetTargetWP: primSetTargetWP,
            primSpanBottom: primSpanBottom,
            primSpanLeft: primSpanLeft,
            primSpanRight: primSpanRight,
            primSpanTop: primSpanTop,
            primStrokeRGBA: primStrokeRGBA,
            primStrokeWidthHop: primStrokeWidthHop,
            primTargetAssumedOpaque: primTargetAssumedOpaque,
            primUpdateContourLastLine: primUpdateContourLastLine,
        });
    } else self.setTimeout(registerPlugin, 100);
}

registerPlugin();

})();
